[build]
  base = "mcleun-app" 
  command = "npm run build"
  publish = "mcleun-app/dist" 
[build.environment]
  NODE_VERSION = "18.20.5"        

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
